### PR TITLE
Merge from upstream

### PR DESCRIPTION
**Pull request by kellyma2**
This PR brings in changes from upstream as of [0c4ea9a](https://github.com/arrikto/oidc-authservice/commit/0c4ea9aa5e962c7f946c1acb65cfae3b0f604817).

it was produced by rebasing the changes from upstream from the previous common commit one by one, resolving conflicts, and dropping commits for things which were done differently upstream.

All our extra feature implementation remains intact and tested

### CODE REVIEW

**Review by devoxel — COMMENTED** [review]
I did one pass on this - it's a pretty gigantic change so I'll probably need to go again.

Overall it looks okay to me. I don't like the `common` package but that's a nitpick. I can't confidently approve it yet - either I need to look again on a per commit basis or somebody else can.

**Comment by ajhfok** [comment]
@devoxel thanks for taking the time to have a look

> I did one pass on this - it's a pretty gigantic change so I'll probably need to go again.

I still need to do my pass, but for context mkelly and I worked on this together (almost like pair programming, but not) so its implicitly had two sets of eyes over it.
 
> Overall it looks okay to me.

Thanks, this is good feedback.

> I don't like the `common` package but that's a nitpick. 

Yeah I have my feelings about it too, but our intention with this was to make our fork looking more like upstream to hopefully make future syncs less painful.

> I can't confidently approve it yet - either I need to look again on a per commit basis or somebody else can.

If you're not confident to give this an "approve" thats ok, I'm happy to eventually approve to let it merge. Its good that at least you (as someone from cvaas) has had at least an eyes over this commit, unless you have any explicit objections to me eventually giving this an approve and letting it merge. Do you think someone from cvaas should give this an approve before merging? or your eyes over is enough for now.

I will do another round of manual testing with this specific branch before I approve

**Comment by asetty** [comment]
Looks good to me at least after doing a first pass.

Do we see it as a possibility of submitting a PR to get in sync with the upstream? 

Also @kellyma2, you mentioned some commits from upstream that were dropped. Curious what was undesirable about those / if theres a way to integrate or make changes after those comm that would enable us to fully get in sync with upstream.

**Comment by ajhfok** [comment]
Answering for @kellyma2 since he's in leave for now

```
Do we see it as a possibility of submitting a PR to get in sync with the upstream?
```
From what Mike said, some of the features we've introduced have been outright rejected by upstream, so I think we'll be maintaining our unique fork for a while

```
Also @kellyma2, you mentioned some commits from upstream that were dropped. Curious what was undesirable about those / if theres a way to integrate or make changes after those comm that would enable us to fully get in sync with upstream.
```
From what I understand, they just sat on many of the PRs, then ended up using the "spirit" of some of Mike's PRs, but implementing them slightly differently (like `authenticator` vs `authenticators`).

**Review by ajhfok — APPROVED** [review]
looked through the changes one more time, they all look good

**Review by asetty — APPROVED** [review]

**Pull request merged**
